### ISSUE TITLE
Non-issue: Pictures 

### ISSUE THREAD

**Issue by TG9541** [TG9541/W1209#2]
Issues can store pictures which can be linked in the Wiki. Let's use this issue for that!

**Comment by TG9541** [comment]
![ntc_epcos_b57164](https://user-images.githubusercontent.com/5466977/29013013-1f501d7e-7b40-11e7-9dc2-edbe6f0da040.png)

**Comment by larsbrinkhoff** [comment]
Interesting solution.  I have been uploading images to ophan branches.

**Comment by TG9541** [comment]
GitHub offers quality infrastructure with lots of features for free, and by combining features one gets new features. In combination with external services, e.g. the Travis-CI deployment feature, it should even be possible to create interesting analytics, and dashboard solutions. a custom project dashboard. Maybe it's possible to combine ReadTheDocs with the GitHub wiki...

In GitHub team pages there is even more to explore (e.g. GitHub Pages, Team Discussions).

**Comment by TG9541** [comment]
![tempchart](https://user-images.githubusercontent.com/5466977/33803418-d4864d56-dd8f-11e7-9062-48678e0ed3e2.png)

**Comment by TG9541** [comment]
![w1209-log2](https://user-images.githubusercontent.com/5466977/34077539-cce83cea-e306-11e7-849c-5c1c5faae08b.png)

**Comment by TG9541** [comment]
![w1209](https://user-images.githubusercontent.com/5466977/34077952-4023969c-e310-11e7-8313-49407c417ac9.png)
