### ISSUE TITLE
Output for "overheat" protection.

### ISSUE THREAD

**Issue by Sean541** [TG9541/W1209#24]
The original W1209 firmware has a configurable overheat protection that shuts off the relay when the temp rises above a set value. I'd like to create a similar feature that, rather than shutting off the relay, signals an external MCU when the set temp is reached. The easiest would be to toggle a GPIO low/high, however it doesn't appear there are any GPIO's available. So I was wondering if a command could be sent over serial instead? Any input appreciated, thanks!

**Comment by paulcrawford** [comment]
Sean,

Yes it is definitely possible. Thomas helped me set up the Forth code to send the present temperature, a serial counter and a CRC on the serial port every 2.5 seconds or so.

Thanks,

Paul

**Comment by Sean541** [comment]
Great, good to know. Could you possibly point me toward any good docs/tutorials/relevant code examples for Forth? I'm decent in C but this is my first exposure to Forth and its specific layout and syntax. My goal here is to make a thermostat controller for the chest freezer in my garage that will both text me and sound a beeper alarm if the temp rises over a preset point. So I thought I'd try an use the W1209 a long with an Arduino that will handle the text and beeper part. The original thermostat quit working a few weeks ago and is a discontinued part. Aside from not wanting to replace a perfectly good large freezer over a small part like the thermostat, I want to add the alarm feature because I never,... and I mean NEVER, want to have to clean out another freezer of food when the first thing that made you realize it quit working was the smell starting to creep out from the seals. BLEH.

**Comment by paulcrawford** [comment]
You could review the code that Thomas and I worked on here:[https://github.com/paulcrawford/W1209](url)

Also there is a great deal of info in this repository about eForth and tools required to set up a W1209 with custom code.

**Comment by TG9541** [comment]
@Sean541 sorry for not responding in a timely manner. 

As @paulcrawford kindly pointed out such a feature is easy to implement (e.g. as a new module in the processing chain or as a new feature of `control.fs`. It might also be interesting to use a different board for such an application, e.g. the C0135. The only thing you'd be missing is a display, but I'm quite sure that one can hack a W1209 to serve as a display.
