### ISSUE TITLE
I'm new at this

### ISSUE THREAD

**Issue by vinnyphx** [TG9541/W1209#25]
I am not a programmer but I learn quickly, my question is can the w1209 be used with a 100k thermoistor and in crease the temperature range? I have a few from other projects but can seem to find  suitable hardware to do the job I need

**Comment by TG9541** [comment]
Hi @vinnyphx, 

the W1209 can be used with a 100k thermistor if (and only if) you exchange a resistor on the PCB and program a suitable linearization function. You also need a compatible W1209 variant (or do some soldering to create one). 

Unless you want to do some soldering and programming the W1209 might not be the best choice.

**Comment by vinnyphx** [comment]
I've worked on pcb, that's not a problem, is the programing terribly complicated? I've looked through a number of the uploaded files, it seems as if i will need to enter the resistance to temperature tables in the measure file. is it much more in-depth than that?

**Comment by TG9541** [comment]
The programming isn't complicated - getting the programming environment right is more complicated (i.e. STLINK programmer, serial interface, etc). It's also possible to work with the programmer only and create the binary through Travis-CI, not with the embedded Forth system.

You´ll have to create a table "temperature to voltage" (which can be done with the help of a modified W1209 board). If the voltage is in the right range (i.e. a the resistor you chose has about the same resistance as the thermistor in the temperature range where the accuracy should be best) then it shouldn't be a problem.
